name: Release Please

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@v2

      - name: Setup Node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install --frozen-lockfile

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: bun run build

      - name: Lint
        if: ${{ steps.release.outputs.release_created }}
        run: bun run lint && bun turbo run lint

      - name: Test
        if: ${{ steps.release.outputs.release_created }}
        run: bun run test

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
